"""
Data Analyst Agent using LangChain + LangGraph
================================================
Accepts one or more CSV/XLSX files, answers user queries with interactive
visualizations and summaries.

Architecture (LangGraph State Machine):
  [START] -> [router] -> [analyze] -> [visualize] -> [summarize] -> [END]
                |                          |
                +-- (summary only) --------+-> [summarize] -> [END]

Nodes:
  - router:     Inspects query & data, decides if visualization is needed
  - analyze:    Runs pandas code to extract insights from the data
  - visualize:  Generates interactive Plotly charts returned as JSON
  - summarize:  Produces a natural language summary of findings

Data profiling (run_profiling) runs separately before the graph and returns
an LLM-generated description of every column in every dataset.
"""

import os
import re
import sys
import json
import time
import pandas as pd
import matplotlib
from dotenv import load_dotenv
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from typing import TypedDict, Literal, Optional, List
from pathlib import Path
from pydantic import BaseModel, Field

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, END

# Load environment variables from .env file
load_dotenv()

# ─── Configuration ───────────────────────────────────────────────────────────
OUTPUT_DIR = Path("./outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

MODEL_NAME = "claude-sonnet-4-6"

# ─── State Schema ────────────────────────────────────────────────────────────
class AgentState(TypedDict):
    """State that flows through the graph."""
    file_paths: List[str]       # list of uploaded file paths
    sheet_names: dict           # {file_path: sheet_name | list[str]} for xlsx files
    file_labels: List[str]      # human-readable labels used as variable name stems
    user_query: str
    df_info: str                # combined string repr of all datasets
    df_json: str                # JSON serialized datasets (for small-medium datasets)
    analysis_code: str          # pandas code generated by LLM
    analysis_result: str        # output from running analysis code
    needs_visualization: bool
    viz_code: str               # plotly code generated by LLM
    viz_json: str               # Plotly figure serialised as JSON (use pio.from_json to render)
    summary: str                # final natural language summary
    error: str                  # error messages if any
    column_profiles: dict       # user-confirmed column profiles {var_name: {shape, columns}}


# ─── Pydantic Schema for Structured Output ──────────────────────────────────
class RouterResponse(BaseModel):
    """Schema for router decision on visualization needs."""
    needs_visualization: bool = Field(description="Whether a visualization would be helpful for the query")
    reasoning: str = Field(description="Brief explanation for the decision")


class SufficiencyResponse(BaseModel):
    """Schema for field-sufficiency validation."""
    sufficient: bool = Field(
        description="True if the selected fields are enough to meaningfully answer the query"
    )
    reason: str = Field(description="One or two sentences explaining why")
    suggested_fields: List[str] = Field(
        default_factory=list,
        description=(
            "If not sufficient, list the specific field names (from the available "
            "but currently excluded fields) the user should also include"
        ),
    )


# ─── Helper: Variable Naming ─────────────────────────────────────────────────
def get_df_variable_name(label: str, index: int) -> str:
    """Generate a safe Python variable name from a file label."""
    safe = re.sub(r'[^a-zA-Z0-9]', '_', label).lower().strip('_')
    if not safe or safe[0].isdigit():
        safe = f"dataset_{index}"
    return f"df_{safe}"


# ─── Helper: Load Data ───────────────────────────────────────────────────────
def load_dataframe(file_path: str, sheet_name: Optional[str] = None) -> pd.DataFrame:
    """Load a single CSV or XLSX file into a DataFrame."""
    ext = Path(file_path).suffix.lower()
    if ext == ".csv":
        return pd.read_csv(file_path)
    elif ext in (".xlsx", ".xls"):
        kwargs = {}
        if sheet_name is not None:
            kwargs["sheet_name"] = sheet_name
        return pd.read_excel(file_path, **kwargs)
    else:
        raise ValueError(f"Unsupported file format: {ext}. Only CSV and XLSX are supported.")


def load_all_dataframes(
    file_paths: List[str],
    sheet_names: Optional[dict] = None,
    file_labels: Optional[List[str]] = None,
) -> dict:
    """Load all files and return an ordered dict of {var_name: DataFrame}.

    sheet_names values may be a single sheet name (str) or a list of sheet
    names.  When multiple sheets are provided for one file, each sheet is
    loaded as its own separate dataset.

    The variable ``df`` is used when exactly one dataset is loaded in total
    (backward-compatible).  With multiple datasets each gets a descriptive
    name, e.g. ``df_sales``, ``df_customers_demographics``.
    """
    if sheet_names is None:
        sheet_names = {}
    if file_labels is None:
        file_labels = [Path(fp).stem for fp in file_paths]

    # Expand (file_path, label) pairs into (file_path, sheet_or_None, label)
    # entries.  A list-valued sheet entry produces one entry per sheet.
    entries: list = []
    for fp, label in zip(file_paths, file_labels):
        sheets_val = sheet_names.get(fp)
        if isinstance(sheets_val, list):
            for sh in sheets_val:
                entries.append((fp, sh, label))
        else:
            entries.append((fp, sheets_val, label))

    total = len(entries)
    dfs: dict = {}
    for i, (fp, sheet, label) in enumerate(entries):
        df = load_dataframe(fp, sheet_name=sheet)

        if total == 1:
            var_name = "df"
        else:
            base = get_df_variable_name(label, i + 1)
            if sheet is not None:
                safe_sheet = re.sub(r"[^a-zA-Z0-9]", "_", sheet).lower().strip("_")
                var_name = f"{base}_{safe_sheet}"
            else:
                var_name = base
            # Resolve collisions
            original = var_name
            suffix = 2
            while var_name in dfs:
                var_name = f"{original}_{suffix}"
                suffix += 1

        dfs[var_name] = df

    return dfs


# ─── Helper: Dataset Info ────────────────────────────────────────────────────
def get_df_info(dfs: dict) -> str:
    """Generate a comprehensive string summary of one or more dataframes."""
    parts = []
    for var_name, df in dfs.items():
        if len(dfs) > 1:
            parts.append("=" * 50)
            parts.append(f"Dataset: `{var_name}`")
            parts.append("=" * 50)
        parts.append(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
        parts.append(f"\nColumns & Types:\n{df.dtypes.to_string()}")
        parts.append(f"\nFirst 5 rows:\n{df.head().to_string()}")
        parts.append(f"\nBasic Statistics:\n{df.describe(include='all').to_string()}")
        null_counts = df.isnull().sum()
        if null_counts.any():
            parts.append(f"\nNull Values:\n{null_counts[null_counts > 0].to_string()}")
        parts.append("")
    return "\n".join(parts)


def _build_dataset_context(dfs: dict) -> str:
    """Return a one-line or bulleted description of available datasets."""
    if len(dfs) == 1:
        var_name, df = next(iter(dfs.items()))
        return (
            f"The dataset is loaded as `{var_name}` "
            f"({df.shape[0]} rows × {df.shape[1]} columns)."
        )
    lines = ["The following datasets are available:"]
    for var_name, df in dfs.items():
        lines.append(f"  - `{var_name}`: {df.shape[0]} rows × {df.shape[1]} columns")
    return "\n".join(lines)


def _build_profile_context(column_profiles: dict) -> str:
    """Format user-confirmed column profiles as a concise LLM context block.

    Only selected columns (use=True) are listed as active; excluded columns
    are noted in aggregate so the LLM knows not to rely on them.
    """
    if not column_profiles:
        return ""
    parts = ["User-confirmed column profiles (focus ONLY on selected fields):"]
    for var_name, info in column_profiles.items():
        parts.append(f"\n  Dataset `{var_name}`:")
        selected, excluded = [], []
        for col in info.get("columns", []):
            nullable_str = "nullable" if col.get("nullable") else "not nullable"
            if col.get("use", True):
                selected.append(
                    f"    ✓ {col['column']} [{col['type']}, {nullable_str}]:"
                    f" {col['description']}"
                )
            else:
                excluded.append(col["column"])
        parts.extend(selected)
        if excluded:
            parts.append(f"    ✗ Excluded by user: {', '.join(excluded)}")
    return "\n".join(parts)


def create_streamlit_summary(result: dict) -> str:
    """Create a Streamlit-compatible summary with the analysis results."""
    summary_parts = ["# Data Analysis Results\n"]
    if result.get("summary"):
        summary_parts.append(f"## Summary\n{result['summary']}\n")
    if result.get("viz_json"):
        summary_parts.append("## Visualization\nInteractive Plotly chart generated.\n")
    if result.get("analysis_code"):
        summary_parts.append(f"## Analysis Code\n```python\n{result['analysis_code']}\n```\n")
    return "".join(summary_parts)


# ─── LLM Setup ───────────────────────────────────────────────────────────────
def get_llm():
    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY environment variable is required.")
    return ChatAnthropic(model=MODEL_NAME, temperature=0, max_tokens=8000)


# ─── Node: Router ────────────────────────────────────────────────────────────
def router_node(state: AgentState) -> AgentState:
    """Load all datasets and decide whether visualization is needed."""
    try:
        dfs = load_all_dataframes(
            state["file_paths"],
            state.get("sheet_names", {}),
            state.get("file_labels", []),
        )
        df_info = get_df_info(dfs)

        # Serialize datasets (limit to first 200 rows each for LLM context)
        df_json_parts: dict = {}
        for var_name, df in dfs.items():
            df_json_parts[var_name] = json.loads(
                df.head(200).to_json(orient="records", date_format="iso")
            )
        df_json = json.dumps(df_json_parts)

        # Ask LLM if visualization is needed
        llm = get_llm()
        structured_llm = llm.with_structured_output(RouterResponse)

        dataset_context = _build_dataset_context(dfs)
        profile_context = _build_profile_context(state.get("column_profiles", {}))
        routing_prompt = f"""You are a data analyst assistant. Given the user's query and the dataset info,
determine if a visualization (chart/graph) would be helpful.

{dataset_context}
{f"{chr(10)}{profile_context}{chr(10)}" if profile_context else ""}
Dataset Info:
{df_info}

User Query: {state['user_query']}

Analyze the query and data to decide if visualization would enhance understanding."""

        try:
            response = structured_llm.invoke([HumanMessage(content=routing_prompt)])
            needs_viz = response.needs_visualization
        except Exception as e:
            print(f"Warning: Structured output failed: {e}. Defaulting visualization=True")
            needs_viz = True

        return {
            **state,
            "df_info": df_info,
            "df_json": df_json,
            "needs_visualization": needs_viz,
            "error": "",
        }
    except Exception as e:
        return {**state, "error": f"Router error: {str(e)}"}


# ─── Node: Analyze ───────────────────────────────────────────────────────────
def analyze_node(state: AgentState) -> AgentState:
    """Generate and execute pandas analysis code."""
    if state.get("error"):
        return state

    llm = get_llm()

    dfs = load_all_dataframes(
        state["file_paths"],
        state.get("sheet_names", {}),
        state.get("file_labels", []),
    )
    dataset_context = _build_dataset_context(dfs)
    profile_context = _build_profile_context(state.get("column_profiles", {}))
    var_list = ", ".join(f"`{name}`" for name in dfs.keys())
    multi = len(dfs) > 1

    analysis_prompt = f"""You are an expert data analyst. Generate Python/pandas code to answer the user's query.

{dataset_context}
{f"{chr(10)}{profile_context}{chr(10)}" if profile_context else ""}
Dataset Info:
{state['df_info']}

User Query: {state['user_query']}

Rules:
1. The dataframe{'s are' if multi else ' is'} already loaded as {var_list}
2. Store your final result in a variable called `result` (as a string)
3. Use pandas operations for analysis
4. Handle potential errors (missing columns, NaN values, etc.)
5. Make the result informative and well-formatted
6. Do NOT import pandas (it's already imported as `pd`)
7. Do NOT print anything, just assign to `result`
{f"8. You may join/merge the datasets if cross-dataset analysis is needed" if multi else ""}

Return ONLY the Python code, no markdown fences or explanations."""

    response = llm.invoke([HumanMessage(content=analysis_prompt)])
    code = response.content.strip()

    # Strip markdown fences if present
    if code.startswith("```"):
        code = "\n".join(code.split("\n")[1:])
    if code.endswith("```"):
        code = "\n".join(code.split("\n")[:-1])

    # Execute the generated code with all dataframes in scope
    try:
        local_vars = {**dfs, "pd": pd}
        exec(code, {"pd": pd, "np": __import__("numpy")}, local_vars)
        result = str(local_vars.get("result", "Analysis complete but no result variable found."))
    except Exception as e:
        result = f"Code execution error: {str(e)}"

    return {
        **state,
        "analysis_code": code,
        "analysis_result": result,
    }


# ─── Node: Visualize ─────────────────────────────────────────────────────────
def visualize_node(state: AgentState) -> AgentState:
    """Generate and execute Plotly visualization code, returning figure JSON."""
    if state.get("error") or not state.get("needs_visualization", False):
        return {**state, "viz_json": ""}

    llm = get_llm()

    dfs = load_all_dataframes(
        state["file_paths"],
        state.get("sheet_names", {}),
        state.get("file_labels", []),
    )
    dataset_context = _build_dataset_context(dfs)
    profile_context = _build_profile_context(state.get("column_profiles", {}))
    var_list = ", ".join(f"`{name}`" for name in dfs.keys())
    multi = len(dfs) > 1

    viz_prompt = f"""You are an expert data visualization specialist. Generate Python code using Plotly \
to create an interactive chart that answers the user's query.

{dataset_context}
{f"{chr(10)}{profile_context}{chr(10)}" if profile_context else ""}

Dataset Info:
{state['df_info']}

Analysis Result:
{state['analysis_result']}

User Query: {state['user_query']}

Rules:
1. The dataframe{'s are' if multi else ' is'} already loaded as {var_list}
2. `plotly.express` is already imported as `px`, `plotly.graph_objects` as `go`
3. `pandas` is imported as `pd`, `numpy` as `np`
4. Create a variable named `fig` (a Plotly Figure object)
5. Choose an appropriate chart type (bar, line, scatter, pie, heatmap, box, violin, etc.)
6. Include a descriptive title, axis labels, and legend where appropriate
7. Use a professional color palette (e.g. px.colors.qualitative.Set2 or Plotly default)
8. Handle edge cases: too many categories → show top N; long labels → abbreviate or rotate
9. Do NOT call fig.show() — only assign to `fig`
10. Do NOT import plotly — it is already imported
{f"11. You may merge/join datasets for the visualization if needed" if multi else ""}

Return ONLY the Python code, no markdown fences or explanations."""

    response = llm.invoke([HumanMessage(content=viz_prompt)])
    code = response.content.strip()

    if code.startswith("```"):
        code = "\n".join(code.split("\n")[1:])
    if code.endswith("```"):
        code = "\n".join(code.split("\n")[:-1])

    viz_json = ""
    try:
        import plotly.express as px
        import plotly.graph_objects as go

        local_vars = {**dfs}
        exec(
            code,
            {
                "pd": pd,
                "np": __import__("numpy"),
                "px": px,
                "go": go,
            },
            local_vars,
        )
        fig = local_vars.get("fig")
        if fig is not None:
            viz_json = fig.to_json()
        else:
            code += "\n# Error: code did not produce a `fig` variable"
    except Exception as e:
        code += f"\n# Visualization error: {str(e)}"

    return {
        **state,
        "viz_code": code,
        "viz_json": viz_json,
    }


# ─── Node: Summarize ────────────────────────────────────────────────────────
def summarize_node(state: AgentState) -> AgentState:
    """Generate a natural language summary of findings."""
    if state.get("error"):
        return {**state, "summary": f"Error occurred: {state['error']}"}

    llm = get_llm()

    num_datasets = len(state.get("file_paths", []))
    dataset_desc = f"{num_datasets} dataset{'s' if num_datasets > 1 else ''}"

    summary_prompt = f"""You are a senior data analyst presenting findings. Write a clear, professional summary.

User Query: {state['user_query']}

Dataset Info ({dataset_desc}):
{state['df_info']}

Analysis Result:
{state['analysis_result']}

Visualization: {"An interactive Plotly chart has been generated." if state.get('viz_json') else "No visualization was generated."}

Write a concise but thorough summary that:
1. Directly answers the user's query
2. Highlights key findings and numbers
3. Notes any interesting patterns or outliers
4. Provides actionable insights where applicable
5. Mentions any data quality issues found

Keep it professional and data-driven."""

    response = llm.invoke([HumanMessage(content=summary_prompt)])
    return {**state, "summary": response.content}


# ─── Conditional Edge ────────────────────────────────────────────────────────
def should_visualize(state: AgentState) -> str:
    """Decide whether to go to visualization or straight to summary."""
    if state.get("error"):
        return "summarize"
    if state.get("needs_visualization", False):
        return "visualize"
    return "summarize"


# ─── Build the Graph ─────────────────────────────────────────────────────────
def build_graph() -> StateGraph:
    """Construct the LangGraph state machine."""
    workflow = StateGraph(AgentState)

    workflow.add_node("router", router_node)
    workflow.add_node("analyze", analyze_node)
    workflow.add_node("visualize", visualize_node)
    workflow.add_node("summarize", summarize_node)

    workflow.set_entry_point("router")
    workflow.add_edge("router", "analyze")
    workflow.add_conditional_edges(
        "analyze",
        should_visualize,
        {
            "visualize": "visualize",
            "summarize": "summarize",
        }
    )
    workflow.add_edge("visualize", "summarize")
    workflow.add_edge("summarize", END)

    return workflow.compile()


# ─── Data Profiling ──────────────────────────────────────────────────────────
def profile_datasets(dfs: dict, user_query: str = "") -> dict:
    """Use the LLM to describe every column in every loaded dataset.

    When user_query is provided the LLM also marks each column as relevant
    or not relevant for answering that specific query.

    Returns a dict structured as:
      {
        var_name: {
          "shape": [rows, cols],
          "columns": [
            {"column": ..., "type": ..., "description": ...,
             "nullable": bool, "relevant": bool, "sample_values": "..."},
            ...
          ]
        },
        ...
      }
    On error, returns {"error": "<message>"}.
    """
    llm = get_llm()
    profiles: dict = {}

    for var_name, df in dfs.items():
        # Build a compact schema for the LLM
        schema = []
        for col in df.columns:
            null_pct = round(float(df[col].isnull().mean()) * 100, 1)
            sample = [str(v) for v in df[col].dropna().head(5).tolist()]
            schema.append({
                "column": col,
                "pandas_dtype": str(df[col].dtype),
                "null_pct": null_pct,
                "unique_count": int(df[col].nunique()),
                "sample_values": sample,
            })

        query_context = (
            f"\nUser's analysis query: \"{user_query}\"\n"
            if user_query else ""
        )

        prompt = f"""You are a data analyst reviewing a dataset schema. Describe each column concisely.
{query_context}
Dataset: `{var_name}` ({df.shape[0]:,} rows × {df.shape[1]} columns)

Schema (JSON):
{json.dumps(schema, indent=2)}

Return a JSON array — one object per column — with EXACTLY these keys:
- "column"       : the column name (string, unchanged)
- "type"         : human-readable type — one of: "string", "integer", "float", \
"boolean", "date", "datetime", "category", "id", "unknown"
- "description"  : one sentence explaining what this field likely represents in a \
business/domain context
- "nullable"     : true if null_pct > 0, else false
- "relevant"     : true if this column would likely be needed to answer the user's \
query, false if it is not needed{" (set all to true if no query provided)" if not user_query else ""}

Return ONLY the JSON array. No markdown fences, no extra text."""

        response = llm.invoke([HumanMessage(content=prompt)])
        raw = response.content.strip()
        # Strip accidental markdown fences
        if raw.startswith("```"):
            raw = re.sub(r"^```[a-z]*\n?", "", raw)
            raw = re.sub(r"\n?```$", "", raw)
        raw = raw.strip()

        try:
            col_profiles = json.loads(raw)
        except Exception:
            # Fallback: build a plain profile without LLM descriptions
            col_profiles = [
                {
                    "column": s["column"],
                    "type": s["pandas_dtype"],
                    "description": "(LLM description unavailable)",
                    "nullable": s["null_pct"] > 0,
                    "relevant": True,
                }
                for s in schema
            ]

        # Attach sample_values from the schema we already built
        schema_by_col = {s["column"]: s for s in schema}
        for item in col_profiles:
            col = item.get("column", "")
            item["sample_values"] = ", ".join(schema_by_col.get(col, {}).get("sample_values", []))
            # Ensure relevant key exists (defensive)
            item.setdefault("relevant", True)

        profiles[var_name] = {
            "shape": list(df.shape),
            "columns": col_profiles,
        }

    return profiles


def check_field_sufficiency(
    query: str,
    selected_columns: dict,
    profile: dict,
) -> dict:
    """Check whether the user-selected fields are sufficient to answer the query.

    Args:
        query:            The user's natural language analysis query.
        selected_columns: {var_name: [selected_col_names]} — fields the user checked.
        profile:          Full profile dict (all columns with descriptions).

    Returns:
        {"sufficient": bool, "reason": str, "suggested_fields": [field_names]}
    """
    llm = get_llm()
    structured_llm = llm.with_structured_output(SufficiencyResponse)

    # Build a readable summary of selected vs available columns per dataset
    lines: list = [f'User query: "{query}"\n']
    for var_name, info in profile.items():
        all_cols = {c["column"]: c for c in info.get("columns", [])}
        sel_names = set(selected_columns.get(var_name, []))
        excluded_names = [c for c in all_cols if c not in sel_names]

        lines.append(f"Dataset `{var_name}`:")
        lines.append("  Selected fields:")
        for name in sel_names:
            col = all_cols.get(name, {})
            lines.append(
                f"    • {name} [{col.get('type', '?')}]: {col.get('description', '')}"
            )
        if excluded_names:
            lines.append("  Available but excluded fields:")
            for name in excluded_names:
                col = all_cols.get(name, {})
                lines.append(
                    f"    • {name} [{col.get('type', '?')}]: {col.get('description', '')}"
                )

    prompt = f"""You are a senior data analyst. Evaluate whether the user's selected \
data fields are sufficient to answer their query.

{chr(10).join(lines)}

Guidelines:
- Be pragmatic: if the query can be meaningfully answered with the selected fields, \
mark it as sufficient even if extra fields might add nuance.
- Only mark as insufficient when a critical field is clearly missing \
(e.g. the query asks about revenue but revenue is excluded).
- If insufficient, list ONLY the specific excluded field names that would fix the gap."""

    try:
        response = structured_llm.invoke([HumanMessage(content=prompt)])
        return {
            "sufficient": response.sufficient,
            "reason": response.reason,
            "suggested_fields": response.suggested_fields,
        }
    except Exception as e:
        # Default to sufficient so errors never block the user
        return {
            "sufficient": True,
            "reason": f"Sufficiency check could not run ({e}). Proceeding with selected fields.",
            "suggested_fields": [],
        }


def run_profiling(
    file_paths,
    sheet_names: Optional[dict] = None,
    file_labels: Optional[List[str]] = None,
    user_query: str = "",
) -> dict:
    """Load datasets and return an LLM-generated column profile for each.

    user_query is forwarded to profile_datasets so the LLM can mark which
    columns are relevant to the specific analysis request.

    Returns the same structure as profile_datasets(), or {"error": "..."} on failure.
    """
    if isinstance(file_paths, str):
        file_paths = [file_paths]
    try:
        dfs = load_all_dataframes(file_paths, sheet_names, file_labels)
        return profile_datasets(dfs, user_query=user_query)
    except Exception as e:
        return {"error": str(e)}


# ─── Main Entry Point ────────────────────────────────────────────────────────
def run_agent(
    file_paths,
    query: str,
    sheet_names: Optional[dict] = None,
    file_labels: Optional[List[str]] = None,
    column_profiles: Optional[dict] = None,
) -> dict:
    """Run the data analyst agent on one or more files with a query.

    Args:
        file_paths:      A single file path string or a list of file paths.
        query:           Natural language analysis question.
        sheet_names:     Optional mapping of {file_path: sheet_name | list[str]}.
        file_labels:     Optional human-readable labels for each file.
        column_profiles: Optional user-confirmed column profiles from the
                         profiling step {var_name: {shape, columns}}.
                         Included in LLM prompts as authoritative schema context.
    """
    if isinstance(file_paths, str):
        file_paths = [file_paths]

    if sheet_names is None:
        sheet_names = {}
    if file_labels is None:
        file_labels = [Path(fp).stem for fp in file_paths]
    if column_profiles is None:
        column_profiles = {}

    graph = build_graph()

    initial_state: AgentState = {
        "file_paths": file_paths,
        "sheet_names": sheet_names,
        "file_labels": file_labels,
        "user_query": query,
        "df_info": "",
        "df_json": "",
        "analysis_code": "",
        "analysis_result": "",
        "needs_visualization": False,
        "viz_code": "",
        "viz_json": "",
        "summary": "",
        "error": "",
        "column_profiles": column_profiles,
    }

    result = graph.invoke(initial_state)
    return result


# ─── CLI Interface ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Data Analyst Agent (LangChain + LangGraph)")
    parser.add_argument("files", nargs="+", help="Path(s) to CSV or XLSX file(s)")
    parser.add_argument("--query", "-q", required=True, help="Analysis query")
    parser.add_argument(
        "--sheets", "-s", nargs="*",
        help="Sheet names for xlsx files (space-separated, same order as files). "
             "Use 'none' to skip for a CSV in between xlsx files.",
    )
    args = parser.parse_args()

    if not os.getenv("ANTHROPIC_API_KEY"):
        print("Set ANTHROPIC_API_KEY environment variable first.")
        sys.exit(1)

    # Build sheet_names mapping
    sheet_names_map: dict = {}
    if args.sheets:
        for fp, sheet in zip(args.files, args.sheets):
            if sheet and sheet.lower() != "none":
                sheet_names_map[fp] = sheet

    print(f"Loading {len(args.files)} file(s):")
    for f in args.files:
        extra = f" (sheet: {sheet_names_map[f]})" if f in sheet_names_map else ""
        print(f"  - {f}{extra}")
    print(f"Query: {args.query}")
    print("=" * 60)

    result = run_agent(args.files, args.query, sheet_names=sheet_names_map)

    if result.get("error"):
        print(f"\nError: {result['error']}")
    else:
        print(f"\nSummary:\n{result['summary']}")
        if result.get("viz_json"):
            print("\nInteractive Plotly chart generated — open in the web UI to view.")
        print(f"\nAnalysis Code:\n{result['analysis_code']}")
