"""
Data Analyst Agent using LangChain + LangGraph
================================================
Accepts one or more CSV/XLSX files, answers user queries with visualizations and summaries.

Architecture (LangGraph State Machine):
  [START] -> [router] -> [analyze] -> [visualize] -> [summarize] -> [END]
                |                          |
                +-- (summary only) --------+-> [summarize] -> [END]

Nodes:
  - router:     Inspects query & data, decides if visualization is needed
  - analyze:    Runs pandas code to extract insights from the data
  - visualize:  Generates matplotlib/seaborn charts saved as PNG
  - summarize:  Produces a natural language summary of findings
"""

import os
import re
import sys
import json
import time
import pandas as pd
import matplotlib
from dotenv import load_dotenv
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from typing import TypedDict, Literal, Optional, List
from pathlib import Path
from pydantic import BaseModel, Field

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, END

# Load environment variables from .env file
load_dotenv()

# ─── Configuration ───────────────────────────────────────────────────────────
OUTPUT_DIR = Path("./outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

MODEL_NAME = "claude-sonnet-4-5-20250929"

# ─── State Schema ────────────────────────────────────────────────────────────
class AgentState(TypedDict):
    """State that flows through the graph."""
    file_paths: List[str]       # list of uploaded file paths
    sheet_names: dict           # {file_path: sheet_name} for xlsx files
    file_labels: List[str]      # human-readable labels used as variable name stems
    user_query: str
    df_info: str                # combined string repr of all datasets
    df_json: str                # JSON serialized datasets (for small-medium datasets)
    analysis_code: str          # pandas code generated by LLM
    analysis_result: str        # output from running analysis code
    needs_visualization: bool
    viz_code: str               # matplotlib/seaborn code
    viz_path: str               # path to saved chart image
    summary: str                # final natural language summary
    error: str                  # error messages if any


# ─── Pydantic Schema for Structured Output ──────────────────────────────────
class RouterResponse(BaseModel):
    """Schema for router decision on visualization needs."""
    needs_visualization: bool = Field(description="Whether a visualization would be helpful for the query")
    reasoning: str = Field(description="Brief explanation for the decision")


# ─── Helper: Variable Naming ─────────────────────────────────────────────────
def get_df_variable_name(label: str, index: int) -> str:
    """Generate a safe Python variable name from a file label."""
    safe = re.sub(r'[^a-zA-Z0-9]', '_', label).lower().strip('_')
    if not safe or safe[0].isdigit():
        safe = f"dataset_{index}"
    return f"df_{safe}"


# ─── Helper: Load Data ───────────────────────────────────────────────────────
def load_dataframe(file_path: str, sheet_name: Optional[str] = None) -> pd.DataFrame:
    """Load a single CSV or XLSX file into a DataFrame."""
    ext = Path(file_path).suffix.lower()
    if ext == ".csv":
        return pd.read_csv(file_path)
    elif ext in (".xlsx", ".xls"):
        kwargs = {}
        if sheet_name is not None:
            kwargs["sheet_name"] = sheet_name
        return pd.read_excel(file_path, **kwargs)
    else:
        raise ValueError(f"Unsupported file format: {ext}. Only CSV and XLSX are supported.")


def load_all_dataframes(
    file_paths: List[str],
    sheet_names: Optional[dict] = None,
    file_labels: Optional[List[str]] = None,
) -> dict:
    """Load all files and return an ordered dict of {var_name: DataFrame}.

    When a single file is provided the variable is named ``df`` for
    backward-compatibility with LLM-generated code that references ``df``.
    With multiple files each dataset gets a descriptive name derived from its
    label (e.g. ``df_sales``, ``df_customers``).
    """
    if sheet_names is None:
        sheet_names = {}
    if file_labels is None:
        file_labels = [Path(fp).stem for fp in file_paths]

    dfs: dict = {}
    for i, (fp, label) in enumerate(zip(file_paths, file_labels)):
        sheet = sheet_names.get(fp)
        df = load_dataframe(fp, sheet_name=sheet)

        if len(file_paths) == 1:
            var_name = "df"
        else:
            var_name = get_df_variable_name(label, i + 1)
            # Resolve collisions
            if var_name in dfs:
                var_name = f"{var_name}_{i + 1}"

        dfs[var_name] = df

    return dfs


# ─── Helper: Dataset Info ────────────────────────────────────────────────────
def get_df_info(dfs: dict) -> str:
    """Generate a comprehensive string summary of one or more dataframes."""
    parts = []
    for var_name, df in dfs.items():
        if len(dfs) > 1:
            parts.append("=" * 50)
            parts.append(f"Dataset: `{var_name}`")
            parts.append("=" * 50)
        parts.append(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
        parts.append(f"\nColumns & Types:\n{df.dtypes.to_string()}")
        parts.append(f"\nFirst 5 rows:\n{df.head().to_string()}")
        parts.append(f"\nBasic Statistics:\n{df.describe(include='all').to_string()}")
        null_counts = df.isnull().sum()
        if null_counts.any():
            parts.append(f"\nNull Values:\n{null_counts[null_counts > 0].to_string()}")
        parts.append("")
    return "\n".join(parts)


def _build_dataset_context(dfs: dict) -> str:
    """Return a one-line or bulleted description of available datasets."""
    if len(dfs) == 1:
        var_name, df = next(iter(dfs.items()))
        return (
            f"The dataset is loaded as `{var_name}` "
            f"({df.shape[0]} rows × {df.shape[1]} columns)."
        )
    lines = ["The following datasets are available:"]
    for var_name, df in dfs.items():
        lines.append(f"  - `{var_name}`: {df.shape[0]} rows × {df.shape[1]} columns")
    return "\n".join(lines)


def create_streamlit_summary(result: dict) -> str:
    """Create a Streamlit-compatible summary with the analysis results."""
    summary_parts = ["# Data Analysis Results\n"]
    if result.get("summary"):
        summary_parts.append(f"## Summary\n{result['summary']}\n")
    if result.get("viz_path"):
        summary_parts.append(f"## Visualization\nChart saved to: `{result['viz_path']}`\n")
    if result.get("analysis_code"):
        summary_parts.append(f"## Analysis Code\n```python\n{result['analysis_code']}\n```\n")
    return "".join(summary_parts)


# ─── LLM Setup ───────────────────────────────────────────────────────────────
def get_llm():
    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY environment variable is required.")
    return ChatAnthropic(model=MODEL_NAME, temperature=0, max_tokens=8000)


# ─── Node: Router ────────────────────────────────────────────────────────────
def router_node(state: AgentState) -> AgentState:
    """Load all datasets and decide whether visualization is needed."""
    try:
        dfs = load_all_dataframes(
            state["file_paths"],
            state.get("sheet_names", {}),
            state.get("file_labels", []),
        )
        df_info = get_df_info(dfs)

        # Serialize datasets (limit to first 200 rows each for LLM context)
        df_json_parts: dict = {}
        for var_name, df in dfs.items():
            df_json_parts[var_name] = json.loads(
                df.head(200).to_json(orient="records", date_format="iso")
            )
        df_json = json.dumps(df_json_parts)

        # Ask LLM if visualization is needed
        llm = get_llm()
        structured_llm = llm.with_structured_output(RouterResponse)

        dataset_context = _build_dataset_context(dfs)
        routing_prompt = f"""You are a data analyst assistant. Given the user's query and the dataset info,
determine if a visualization (chart/graph) would be helpful.

{dataset_context}

Dataset Info:
{df_info}

User Query: {state['user_query']}

Analyze the query and data to decide if visualization would enhance understanding."""

        try:
            response = structured_llm.invoke([HumanMessage(content=routing_prompt)])
            needs_viz = response.needs_visualization
        except Exception as e:
            print(f"Warning: Structured output failed: {e}. Defaulting visualization=True")
            needs_viz = True

        return {
            **state,
            "df_info": df_info,
            "df_json": df_json,
            "needs_visualization": needs_viz,
            "error": "",
        }
    except Exception as e:
        return {**state, "error": f"Router error: {str(e)}"}


# ─── Node: Analyze ───────────────────────────────────────────────────────────
def analyze_node(state: AgentState) -> AgentState:
    """Generate and execute pandas analysis code."""
    if state.get("error"):
        return state

    llm = get_llm()

    dfs = load_all_dataframes(
        state["file_paths"],
        state.get("sheet_names", {}),
        state.get("file_labels", []),
    )
    dataset_context = _build_dataset_context(dfs)
    var_list = ", ".join(f"`{name}`" for name in dfs.keys())
    multi = len(dfs) > 1

    analysis_prompt = f"""You are an expert data analyst. Generate Python/pandas code to answer the user's query.

{dataset_context}

Dataset Info:
{state['df_info']}

User Query: {state['user_query']}

Rules:
1. The dataframe{'s are' if multi else ' is'} already loaded as {var_list}
2. Store your final result in a variable called `result` (as a string)
3. Use pandas operations for analysis
4. Handle potential errors (missing columns, NaN values, etc.)
5. Make the result informative and well-formatted
6. Do NOT import pandas (it's already imported as `pd`)
7. Do NOT print anything, just assign to `result`
{f"8. You may join/merge the datasets if cross-dataset analysis is needed" if multi else ""}

Return ONLY the Python code, no markdown fences or explanations."""

    response = llm.invoke([HumanMessage(content=analysis_prompt)])
    code = response.content.strip()

    # Strip markdown fences if present
    if code.startswith("```"):
        code = "\n".join(code.split("\n")[1:])
    if code.endswith("```"):
        code = "\n".join(code.split("\n")[:-1])

    # Execute the generated code with all dataframes in scope
    try:
        local_vars = {**dfs, "pd": pd}
        exec(code, {"pd": pd, "np": __import__("numpy")}, local_vars)
        result = str(local_vars.get("result", "Analysis complete but no result variable found."))
    except Exception as e:
        result = f"Code execution error: {str(e)}"

    return {
        **state,
        "analysis_code": code,
        "analysis_result": result,
    }


# ─── Node: Visualize ────────────────────────────────────────────────────────
def visualize_node(state: AgentState) -> AgentState:
    """Generate and execute visualization code."""
    if state.get("error") or not state.get("needs_visualization", False):
        return {**state, "viz_path": ""}

    llm = get_llm()

    dfs = load_all_dataframes(
        state["file_paths"],
        state.get("sheet_names", {}),
        state.get("file_labels", []),
    )
    dataset_context = _build_dataset_context(dfs)
    var_list = ", ".join(f"`{name}`" for name in dfs.keys())
    multi = len(dfs) > 1

    viz_prompt = f"""You are an expert data visualization specialist. Generate Python code using matplotlib and/or seaborn
to create a visualization that answers the user's query.

{dataset_context}

Dataset Info:
{state['df_info']}

Analysis Result:
{state['analysis_result']}

User Query: {state['user_query']}

Rules:
1. The dataframe{'s are' if multi else ' is'} already loaded as {var_list}
2. matplotlib.pyplot is imported as `plt`, seaborn as `sns`
3. Create a clear, professional visualization
4. Use appropriate chart type (bar, line, scatter, pie, heatmap, etc.)
5. Include title, axis labels, and legend where appropriate
6. Use a clean style (sns.set_style("whitegrid") is already applied)
7. Save the figure with: plt.savefig(viz_path, dpi=150, bbox_inches='tight')
8. The variable `viz_path` is already defined with the output path
9. Call plt.close() at the end
10. Handle edge cases (too many categories → top N, long labels → rotation, etc.)
11. Use a pleasing color palette
{f"12. You may combine/merge datasets for the visualization if needed" if multi else ""}

Return ONLY the Python code, no markdown fences or explanations."""

    response = llm.invoke([HumanMessage(content=viz_prompt)])
    code = response.content.strip()

    if code.startswith("```"):
        code = "\n".join(code.split("\n")[1:])
    if code.endswith("```"):
        code = "\n".join(code.split("\n")[:-1])

    viz_path = str(OUTPUT_DIR / f"chart_{int(time.time())}.png")

    try:
        sns.set_style("whitegrid")
        plt.rcParams.update({"figure.figsize": (12, 8), "font.size": 11})

        local_vars = {**dfs, "plt": plt, "sns": sns, "viz_path": viz_path}
        exec(code, {
            "pd": pd,
            "np": __import__("numpy"),
            "plt": plt,
            "sns": sns,
            "matplotlib": matplotlib,
            "time": __import__("time"),
        }, local_vars)

        # Ensure figure is saved even if generated code didn't explicitly save
        if not Path(viz_path).exists():
            plt.savefig(viz_path, dpi=150, bbox_inches="tight")
            plt.close()

    except Exception as e:
        viz_path = ""
        code += f"\n# Visualization error: {str(e)}"
        plt.close("all")

    return {
        **state,
        "viz_code": code,
        "viz_path": viz_path,
    }


# ─── Node: Summarize ────────────────────────────────────────────────────────
def summarize_node(state: AgentState) -> AgentState:
    """Generate a natural language summary of findings."""
    if state.get("error"):
        return {**state, "summary": f"Error occurred: {state['error']}"}

    llm = get_llm()

    num_datasets = len(state.get("file_paths", []))
    dataset_desc = f"{num_datasets} dataset{'s' if num_datasets > 1 else ''}"

    summary_prompt = f"""You are a senior data analyst presenting findings. Write a clear, professional summary.

User Query: {state['user_query']}

Dataset Info ({dataset_desc}):
{state['df_info']}

Analysis Result:
{state['analysis_result']}

Visualization: {"A chart has been generated and saved." if state.get('viz_path') else "No visualization was generated."}

Write a concise but thorough summary that:
1. Directly answers the user's query
2. Highlights key findings and numbers
3. Notes any interesting patterns or outliers
4. Provides actionable insights where applicable
5. Mentions any data quality issues found

Keep it professional and data-driven."""

    response = llm.invoke([HumanMessage(content=summary_prompt)])
    return {**state, "summary": response.content}


# ─── Conditional Edge ────────────────────────────────────────────────────────
def should_visualize(state: AgentState) -> str:
    """Decide whether to go to visualization or straight to summary."""
    if state.get("error"):
        return "summarize"
    if state.get("needs_visualization", False):
        return "visualize"
    return "summarize"


# ─── Build the Graph ─────────────────────────────────────────────────────────
def build_graph() -> StateGraph:
    """Construct the LangGraph state machine."""
    workflow = StateGraph(AgentState)

    workflow.add_node("router", router_node)
    workflow.add_node("analyze", analyze_node)
    workflow.add_node("visualize", visualize_node)
    workflow.add_node("summarize", summarize_node)

    workflow.set_entry_point("router")
    workflow.add_edge("router", "analyze")
    workflow.add_conditional_edges(
        "analyze",
        should_visualize,
        {
            "visualize": "visualize",
            "summarize": "summarize",
        }
    )
    workflow.add_edge("visualize", "summarize")
    workflow.add_edge("summarize", END)

    return workflow.compile()


# ─── Main Entry Point ────────────────────────────────────────────────────────
def run_agent(
    file_paths,
    query: str,
    sheet_names: Optional[dict] = None,
    file_labels: Optional[List[str]] = None,
) -> dict:
    """Run the data analyst agent on one or more files with a query.

    Args:
        file_paths:   A single file path string or a list of file paths.
        query:        Natural language analysis question.
        sheet_names:  Optional mapping of {file_path: sheet_name} for xlsx files.
        file_labels:  Optional human-readable labels for each file (used as
                      Python variable name stems, e.g. "sales" → ``df_sales``).
    """
    # Normalize to list
    if isinstance(file_paths, str):
        file_paths = [file_paths]

    if sheet_names is None:
        sheet_names = {}
    if file_labels is None:
        file_labels = [Path(fp).stem for fp in file_paths]

    graph = build_graph()

    initial_state: AgentState = {
        "file_paths": file_paths,
        "sheet_names": sheet_names,
        "file_labels": file_labels,
        "user_query": query,
        "df_info": "",
        "df_json": "",
        "analysis_code": "",
        "analysis_result": "",
        "needs_visualization": False,
        "viz_code": "",
        "viz_path": "",
        "summary": "",
        "error": "",
    }

    result = graph.invoke(initial_state)
    return result


# ─── CLI Interface ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Data Analyst Agent (LangChain + LangGraph)")
    parser.add_argument("files", nargs="+", help="Path(s) to CSV or XLSX file(s)")
    parser.add_argument("--query", "-q", required=True, help="Analysis query")
    parser.add_argument(
        "--sheets", "-s", nargs="*",
        help="Sheet names for xlsx files (space-separated, same order as files). "
             "Use 'none' to skip for a CSV in between xlsx files.",
    )
    args = parser.parse_args()

    if not os.getenv("ANTHROPIC_API_KEY"):
        print("Set ANTHROPIC_API_KEY environment variable first.")
        sys.exit(1)

    # Build sheet_names mapping
    sheet_names_map: dict = {}
    if args.sheets:
        for fp, sheet in zip(args.files, args.sheets):
            if sheet and sheet.lower() != "none":
                sheet_names_map[fp] = sheet

    print(f"Loading {len(args.files)} file(s):")
    for f in args.files:
        extra = f" (sheet: {sheet_names_map[f]})" if f in sheet_names_map else ""
        print(f"  - {f}{extra}")
    print(f"Query: {args.query}")
    print("=" * 60)

    result = run_agent(args.files, args.query, sheet_names=sheet_names_map)

    if result.get("error"):
        print(f"\nError: {result['error']}")
    else:
        print(f"\nSummary:\n{result['summary']}")
        if result.get("viz_path"):
            print(f"\nChart saved to: {result['viz_path']}")
        print(f"\nAnalysis Code:\n{result['analysis_code']}")
