"""
Data Analyst Agent using LangChain + LangGraph
================================================
Accepts CSV/XLSX files, answers user queries with visualizations and summaries.

Architecture (LangGraph State Machine):
  [START] -> [router] -> [analyze] -> [visualize] -> [summarize] -> [END]
                |                          |
                +-- (summary only) --------+-> [summarize] -> [END]

Nodes:
  - router:     Inspects query & data, decides if visualization is needed
  - analyze:    Runs pandas code to extract insights from the data
  - visualize:  Generates matplotlib/seaborn charts saved as PNG
  - summarize:  Produces a natural language summary of findings
"""

import os
import sys
import json
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from typing import TypedDict, Annotated, Literal, Optional
from pathlib import Path

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, END

# ─── Configuration ───────────────────────────────────────────────────────────
OUTPUT_DIR = Path("./outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

MODEL_NAME = "claude-sonnet-4-20250514"

# ─── State Schema ────────────────────────────────────────────────────────────
class AgentState(TypedDict):
    """State that flows through the graph."""
    file_path: str
    user_query: str
    df_info: str            # string repr of dataframe shape, dtypes, head
    df_json: str            # JSON serialized dataframe (for small-medium datasets)
    analysis_code: str      # pandas code generated by LLM
    analysis_result: str    # output from running analysis code
    needs_visualization: bool
    viz_code: str           # matplotlib/seaborn code
    viz_path: str           # path to saved chart image
    summary: str            # final natural language summary
    error: str              # error messages if any


# ─── Helper: Load Data ───────────────────────────────────────────────────────
def load_dataframe(file_path: str) -> pd.DataFrame:
    """Load CSV or XLSX into a DataFrame."""
    ext = Path(file_path).suffix.lower()
    if ext == ".csv":
        return pd.read_csv(file_path)
    elif ext in (".xlsx", ".xls"):
        return pd.read_excel(file_path)
    else:
        raise ValueError(f"Unsupported file format: {ext}. Only CSV and XLSX are supported.")


def get_df_info(df: pd.DataFrame) -> str:
    """Generate a comprehensive string summary of the dataframe."""
    info_parts = []
    info_parts.append(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
    info_parts.append(f"\nColumns & Types:\n{df.dtypes.to_string()}")
    info_parts.append(f"\nFirst 5 rows:\n{df.head().to_string()}")
    info_parts.append(f"\nBasic Statistics:\n{df.describe(include='all').to_string()}")
    
    # Null counts
    null_counts = df.isnull().sum()
    if null_counts.any():
        info_parts.append(f"\nNull Values:\n{null_counts[null_counts > 0].to_string()}")
    
    return "\n".join(info_parts)


# ─── LLM Setup ───────────────────────────────────────────────────────────────
def get_llm():
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY environment variable is required.")
    return ChatAnthropic(model=MODEL_NAME, temperature=0, max_tokens=4096)


# ─── Node: Router ────────────────────────────────────────────────────────────
def router_node(state: AgentState) -> AgentState:
    """Load data and decide whether visualization is needed."""
    try:
        df = load_dataframe(state["file_path"])
        df_info = get_df_info(df)
        
        # Serialize dataframe (limit to first 500 rows for LLM context)
        df_sample = df.head(500)
        df_json = df_sample.to_json(orient="records", date_format="iso")
        
        # Ask LLM if visualization is needed
        llm = get_llm()
        routing_prompt = f"""You are a data analyst assistant. Given the user's query and the dataset info, 
determine if a visualization (chart/graph) would be helpful.

Dataset Info:
{df_info}

User Query: {state['user_query']}

Respond with ONLY a JSON object: {{"needs_visualization": true/false, "reasoning": "brief reason"}}
"""
        response = llm.invoke([HumanMessage(content=routing_prompt)])
        
        try:
            result = json.loads(response.content)
            needs_viz = result.get("needs_visualization", True)
        except json.JSONDecodeError:
            needs_viz = True  # default to showing visualization
        
        return {
            **state,
            "df_info": df_info,
            "df_json": df_json,
            "needs_visualization": needs_viz,
            "error": "",
        }
    except Exception as e:
        return {**state, "error": f"Router error: {str(e)}"}


# ─── Node: Analyze ───────────────────────────────────────────────────────────
def analyze_node(state: AgentState) -> AgentState:
    """Generate and execute pandas analysis code."""
    if state.get("error"):
        return state
    
    llm = get_llm()
    
    analysis_prompt = f"""You are an expert data analyst. Generate Python/pandas code to answer the user's query.

Dataset Info:
{state['df_info']}

User Query: {state['user_query']}

Rules:
1. The dataframe is already loaded as `df`
2. Store your final result in a variable called `result` (as a string)
3. Use pandas operations for analysis
4. Handle potential errors (missing columns, NaN values, etc.)
5. Make the result informative and well-formatted
6. Do NOT import pandas (it's already imported)
7. Do NOT print anything, just assign to `result`

Return ONLY the Python code, no markdown fences or explanations."""

    response = llm.invoke([HumanMessage(content=analysis_prompt)])
    code = response.content.strip()
    
    # Clean up code (remove markdown fences if any)
    if code.startswith("```"):
        code = "\n".join(code.split("\n")[1:])
    if code.endswith("```"):
        code = "\n".join(code.split("\n")[:-1])
    
    # Execute the code
    try:
        df = load_dataframe(state["file_path"])
        local_vars = {"df": df, "pd": pd}
        exec(code, {"pd": pd, "np": __import__("numpy")}, local_vars)
        result = str(local_vars.get("result", "Analysis complete but no result variable found."))
    except Exception as e:
        result = f"Code execution error: {str(e)}"
    
    return {
        **state,
        "analysis_code": code,
        "analysis_result": result,
    }


# ─── Node: Visualize ────────────────────────────────────────────────────────
def visualize_node(state: AgentState) -> AgentState:
    """Generate and execute visualization code."""
    if state.get("error") or not state.get("needs_visualization", False):
        return {**state, "viz_path": ""}
    
    llm = get_llm()
    
    viz_prompt = f"""You are an expert data visualization specialist. Generate Python code using matplotlib and/or seaborn 
to create a visualization that answers the user's query.

Dataset Info:
{state['df_info']}

Analysis Result:
{state['analysis_result']}

User Query: {state['user_query']}

Rules:
1. The dataframe is already loaded as `df`
2. matplotlib.pyplot is imported as `plt`, seaborn as `sns`
3. Create a clear, professional visualization
4. Use appropriate chart type (bar, line, scatter, pie, heatmap, etc.)
5. Include title, axis labels, and legend where appropriate
6. Use a clean style (sns.set_style("whitegrid") is already applied)
7. Save the figure with: plt.savefig(viz_path, dpi=150, bbox_inches='tight')
8. The variable `viz_path` is already defined with the output path
9. Call plt.close() at the end
10. Handle edge cases (too many categories → top N, long labels → rotation, etc.)
11. Use a pleasing color palette

Return ONLY the Python code, no markdown fences or explanations."""

    response = llm.invoke([HumanMessage(content=viz_prompt)])
    code = response.content.strip()
    
    if code.startswith("```"):
        code = "\n".join(code.split("\n")[1:])
    if code.endswith("```"):
        code = "\n".join(code.split("\n")[:-1])
    
    viz_path = str(OUTPUT_DIR / "chart.png")
    
    try:
        df = load_dataframe(state["file_path"])
        sns.set_style("whitegrid")
        plt.rcParams.update({"figure.figsize": (12, 7), "font.size": 12})
        
        local_vars = {"df": df, "plt": plt, "sns": sns, "viz_path": viz_path}
        exec(code, {
            "pd": pd,
            "np": __import__("numpy"),
            "plt": plt,
            "sns": sns,
            "matplotlib": matplotlib,
        }, local_vars)
        
        # Ensure figure is saved even if code didn't explicitly save
        if not Path(viz_path).exists():
            plt.savefig(viz_path, dpi=150, bbox_inches="tight")
            plt.close()
            
    except Exception as e:
        viz_path = ""
        code += f"\n# Visualization error: {str(e)}"
        plt.close("all")
    
    return {
        **state,
        "viz_code": code,
        "viz_path": viz_path,
    }


# ─── Node: Summarize ────────────────────────────────────────────────────────
def summarize_node(state: AgentState) -> AgentState:
    """Generate a natural language summary of findings."""
    if state.get("error"):
        return {**state, "summary": f"Error occurred: {state['error']}"}
    
    llm = get_llm()
    
    summary_prompt = f"""You are a senior data analyst presenting findings. Write a clear, professional summary.

User Query: {state['user_query']}

Dataset Info:
{state['df_info']}

Analysis Result:
{state['analysis_result']}

Visualization: {"A chart has been generated and saved." if state.get('viz_path') else "No visualization was generated."}

Write a concise but thorough summary that:
1. Directly answers the user's query
2. Highlights key findings and numbers
3. Notes any interesting patterns or outliers
4. Provides actionable insights where applicable
5. Mentions any data quality issues found

Keep it professional and data-driven."""

    response = llm.invoke([HumanMessage(content=summary_prompt)])
    
    return {**state, "summary": response.content}


# ─── Conditional Edge ────────────────────────────────────────────────────────
def should_visualize(state: AgentState) -> str:
    """Decide whether to go to visualization or straight to summary."""
    if state.get("error"):
        return "summarize"
    if state.get("needs_visualization", False):
        return "visualize"
    return "summarize"


# ─── Build the Graph ─────────────────────────────────────────────────────────
def build_graph() -> StateGraph:
    """Construct the LangGraph state machine."""
    workflow = StateGraph(AgentState)
    
    # Add nodes
    workflow.add_node("router", router_node)
    workflow.add_node("analyze", analyze_node)
    workflow.add_node("visualize", visualize_node)
    workflow.add_node("summarize", summarize_node)
    
    # Define edges
    workflow.set_entry_point("router")
    workflow.add_edge("router", "analyze")
    workflow.add_conditional_edges(
        "analyze",
        should_visualize,
        {
            "visualize": "visualize",
            "summarize": "summarize",
        }
    )
    workflow.add_edge("visualize", "summarize")
    workflow.add_edge("summarize", END)
    
    return workflow.compile()


# ─── Main Entry Point ────────────────────────────────────────────────────────
def run_agent(file_path: str, query: str) -> dict:
    """Run the data analyst agent on a file with a query."""
    graph = build_graph()
    
    initial_state: AgentState = {
        "file_path": file_path,
        "user_query": query,
        "df_info": "",
        "df_json": "",
        "analysis_code": "",
        "analysis_result": "",
        "needs_visualization": False,
        "viz_code": "",
        "viz_path": "",
        "summary": "",
        "error": "",
    }
    
    result = graph.invoke(initial_state)
    return result


# ─── CLI Interface ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Data Analyst Agent (LangChain + LangGraph)")
    parser.add_argument("file", help="Path to CSV or XLSX file")
    parser.add_argument("query", help="Analysis query")
    args = parser.parse_args()
    
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("⚠️  Set ANTHROPIC_API_KEY environment variable first.")
        sys.exit(1)
    
    print(f"📂 Loading: {args.file}")
    print(f"❓ Query: {args.query}")
    print("=" * 60)
    
    result = run_agent(args.file, args.query)
    
    if result.get("error"):
        print(f"\n❌ Error: {result['error']}")
    else:
        print(f"\n📊 Summary:\n{result['summary']}")
        if result.get("viz_path"):
            print(f"\n📈 Chart saved to: {result['viz_path']}")
        print(f"\n🔍 Analysis Code:\n{result['analysis_code']}")
